3 спринт
axperien/middle.messenger.praktikum.yandex pull request #5
Opened 2022-06-05 14:20 UTC by axperien

2022-06-05 14:54 UTC, axperien commented
Есть проблемы с архитектурой, некоторые вещи сделаны по принципу - главное чтобы работало, т.к. времени не хватает

2022-06-05 16:54 UTC, podlovchenko requested changes
Привет, очень красивый дизайн приложения и система корректно работает 👍
Есть несколько замечаний:
1. Слишком частое использование ts-ignore, теряются все преимущества использования typescript
2. Нужно настроить eslint так, чтобы не выключать правила в каждом файле
3. Есть классы store и router, но они почему-то не используются

2022-06-05 16:54 UTC, podlovchenko commented on src/utils/apiTransform.ts
> +export const transformChat = (data) => ({
Не стоит злоупотреблять использованием @ts-ignore, в данном случае лучше определить тип для data, это поможет избежать ошибок при вызове функции

2022-06-05 16:54 UTC, podlovchenko commented on src/utils/apiTransform.ts
> +    avatar: data.avatar ? `https://ya-praktikum.tech/api/v2/resources${data.avatar}` : '',
Используется в нескольких местах, было бы хорошо вынести функцию getAvatarUrl

2022-06-05 16:54 UTC, podlovchenko commented on src/utils/apiCheck.ts
> +export const isPing = (response: any) => response && response.type === 'pong';
```suggestion
export const isPing = (response: any) => response?.type === 'pong';
```

2022-06-05 16:54 UTC, podlovchenko commented on src/services/webSocket.ts
> +/* eslint-disable no-constructor-return */
Нужно настроить eslint под свои нужды так, чтобы не приходилось в каждом файле выключать правила

2022-06-05 16:54 UTC, podlovchenko commented on src/services/user.ts
> +        });
Для хранилища лучше создать класс

2022-06-05 16:54 UTC, podlovchenko commented on src/api/apiAuth.ts
> +            timeout: 0,
Если по всему проекту используется timeout 0, то лучше задать как параметр по умолчанию

2022-06-05 16:54 UTC, podlovchenko commented on src/core/HTTPTransport.ts
> +    public request = (url:string, options:HTTPTransportOptions, timeout = 5000) => {
timeout нигде не используется

2022-06-05 16:54 UTC, podlovchenko commented on src/services/auth.ts
> +    window.router.go('/messenger');
Есть же класс Router, почему не используешь его?

2022-06-07 13:30 UTC, axperien commented on src/utils/apiTransform.ts
> +export const transformChat = (data) => ({
Торопился, хотел сдать 3 спринт в срок)

2022-06-07 13:31 UTC, axperien commented on src/services/webSocket.ts
> +/* eslint-disable no-constructor-return */
Торопился, хотел сдать 3 спринт в срок) 
Eslint с настройками airbnb жестковат слегка мне кажется) Добавил исключения правил, остальное поправил

2022-06-07 13:32 UTC, axperien commented on src/services/user.ts
> +        });
Не допер сразу использовать синглтон для стора и роутера. Самый простой вариант был - записать куда нибудь в глобальную видимость

2022-06-07 13:35 UTC, axperien commented
Про аватар по заданию профукал в спешке =/
Ошибку при сборке поправил, она была предупреждающей об использовании babel.config для тестов, когда в parcel уже используется Babel

По stylelint поправил все моменты, кроме предупреждений от prettier по поводу отступов/табуляции. Нагуглил что prettier не умеет проверять пробелы у scss. Насколько это критично?

2022-06-07 16:11 UTC, podlovchenko approved these changes
Все хорошо, работу принимаю)

2022-06-08 07:59 UTC, merged